name: 'Create an Organization | User Repository'
description: 'Creates an Organization Repository and adds the Actor as an admin'
branding:
  icon: 'folder-plus'
  color: 'blue'
inputs:
  repo-name:
    description: 'What is the name of the repository?'
    required: true
    default: ''
  token:
    description: 'Personal access token'
    required: true
    default: ''
  private:
    description: 'Is private repository?'
    type: boolean
    default: false
outputs:
  repo-url:
    description: 'URL of the created repository'
runs:
  using: 'node16'
  main: 'dist/index.js'